# Generated by Django 3.2.5 on 2021-08-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('eamil', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], default='eamil', max_length=50),
        ),
    ]
